name: ci-build

on:
  push:
    branches: [ main, release/** ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Docs
      run: cargo doc --all-features
      env:
        RUSTDOCFLAGS: -Dwarnings

  build-binaries:
    name: build-binaries (${{ matrix.rust-toolchain.label }})
    strategy:
      matrix:
        rust-toolchain: [
          {
            # MSRV from Cargo.toml
            version: "1.89",
            label: "MSRV",
          },
          {
            version: "stable",
            label: "stable"
          },
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-toolchain.version }}
        components: clippy
    - name: Build
      run: cargo build --verbose --package prio-binaries
    - name: Clippy
      run: cargo clippy --package prio-binaries

  build-crate:
    name: build-crate (${{ matrix.rust-toolchain.label }})
    strategy:
      matrix:
        rust-toolchain: [
          {
            # MSRV from Cargo.toml
            version: "1.89",
            label: "MSRV",
          },
          {
            version: "stable",
            label: "stable"
          },
        ]
    runs-on: ubuntu-latest
    env:
      CARGO_ALL_FEATURES_VERSION: 1.9.0
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-toolchain.version }}
        components: clippy, rustfmt
    - name: Cache cargo-all-features
      uses: actions/cache@v6.1.0
      with:
        key: cargo-all-features-bins-${{ env.CARGO_ALL_FEATURES_VERSION }}-rust-${{ matrix.rust-toolchain.version }}
        path: |
          ${{ runner.tool_cache }}/cargo-build-all-features
          ${{ runner.tool_cache }}/cargo-check-all-features
          ${{ runner.tool_cache }}/cargo-test-all-features
    - name: Add the tool cache directory to the search path
      run: echo "${{ runner.tool_cache }}/cargo-all-features/bin/" >> $GITHUB_PATH
    - name: Ensure that the tool cache is populated with the cargo-all-features binaries
      run: |
        cargo install --root ${{ runner.tool_cache }}/cargo-all-features \
          --version ${{ env.CARGO_ALL_FEATURES_VERSION }} \
          cargo-all-features

    - name: Lint
      run: |
        cargo fmt --message-format human -- --check
        bash -c '! git grep "[I][P][D][F]"'
    - name: Check
      run: cargo check-all-features --workspace --all-targets
    - name: Clippy
      run: cargo clippy --workspace --all-targets
    - name: Clippy (all features)
      run: cargo clippy --workspace --all-targets --all-features
    - name: Build crate
      run: cargo build-all-features --verbose --package prio
    - name: Run tests
      run: cargo test-all-features --verbose
    - name: Build benchmarks
      run: cargo bench --no-run --profile=dev
    - name: Build benchmarks (all features)
      run: cargo bench --no-run --profile=dev --all-features

  check-public-dependencies:
    name: check that types from dependencies are not unintentionally exposed in API
    strategy:
      matrix:
        flags: ["--no-default-features", "", "--all-features"]
    runs-on: ubuntu-latest
    env:
      CARGO_CHECK_EXTERNAL_TYPES_VERSION: 0.5.0
    steps:
    - uses: actions/checkout@v7.0.1
    # We have to install a nightly version that uses a rustdoc JSON format that matches what
    # check-external-types expects
    # https://github.com/awslabs/cargo-check-external-types/blob/main/rust-toolchain.toml
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2026-03-20
    - name: Cache cargo-check-external-types
      uses: actions/cache@v6.1.0
      with:
        key: cargo-check-external-types-bin-${{ env.CARGO_CHECK_EXTERNAL_TYPES_VERSION }}-rust-nightly-2026-03-20
        path: ${{ runner.tool_cache }}/cargo-check-external-types
    - name: Add the tool cache directory to the search path
      run: echo "${{ runner.tool_cache }}/cargo-check-external-types/bin/" >> $GITHUB_PATH
    - name: Ensure that the tool cache is populated with the cargo-check-external-types binary
      run: |
        cargo install --root ${{ runner.tool_cache }}/cargo-check-external-types \
          --version ${{ env.CARGO_CHECK_EXTERNAL_TYPES_VERSION }} \
          cargo-check-external-types
    - name: check exported public dependencies
      run: cargo check-external-types ${{ matrix.flags }}
